version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "frab-revalida"
s3_bucket = "revalida-m"
s3_prefix = "frab-revalida"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

