AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  frab-revalida
Globals:
  Function:
    Timeout: 60

Resources:
  BookNewRideFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: book_new_ride/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBWritePolicy:
            TableName:
              !Ref FrabTable
      Events:
        BookNewRideApi:
          Type: Api
          Properties:
            Path: /rides
            Method: post
  
  GetRideInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_ride_info/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref FrabTable
      Events:
         GetRideInfoApi:
          Type: Api
          Properties:
            Path: /rides/{rideId}
            Method: get

  UpdateLocationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: update_location/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref FrabTable
      Events:
        UpdateLocationApi:
          Type: Api
          Properties:
            Path: /{riderType}/{riderId}/locations
            Method: put
  
  GetLocationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_location/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref FrabTable
      Events:
        GetLocationApi:
          Type: Api
          Properties:
            Path: /{riderType}/{riderId}/
            Method: get

  AcceptRideRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: accept_ride_request/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref FrabTable
      Events:
        AcceptRideRequestApi:
          Type: Api
          Properties:
            Path: /drivers/{driverId}/rides/{rideId}/accept
            Method: put
            
  ReturnAcceptableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: return_acceptable_rides/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              !Ref FrabTable
      Events:
        AcceptRideRequestApi:
          Type: Api
          Properties:
            Path: /drivers/{driverId}/rides/acceptable
            Method: get

  ComputeDistanceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: compute_distance/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref FrabTable
      Events:
        AcceptRideRequestApi:
          Type: Api
          Properties:
            Path: /drivers/{driverId}/distance
            Method: put

  FrabBasicAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: authorizer/
      Handler: app.handler
      Runtime: nodejs12.x
  
  GatewayResponse:
    Type: AWS::ApiGateway::GatewayResponse
    Properties: 
      ResponseParameters:
        gatewayresponse.header.WWW-Authenticate: "'Basic'"
      ResponseType: UNAUTHORIZED
      RestApiId: !Sub "${ServerlessRestApi}"
      StatusCode: 401

  FrabTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "datePendingState"
          AttributeType: "S"
        - AttributeName: "state"
          AttributeType: "S"
        - AttributeName: "driverIdKey"
          AttributeType: "S"
        - AttributeName: "stateDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "frab_revalida"
      GlobalSecondaryIndexes:
        - IndexName: "frab_inverted_index"
          KeySchema:
            - AttributeName: "SK"
              KeyType: "HASH"
            - AttributeName: "PK"
              KeyType: "RANGE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "timestamp"
              - "location"
              - "state"
              - "driverId"
              - "locationId"
        - IndexName: "frab_pending_rides"
          KeySchema:
            - AttributeName: "state"
              KeyType: "HASH"
            - AttributeName: "datePendingState"
              KeyType: "RANGE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "bookingLocation"
              - "rideId"
        - IndexName: "frab_ride_state_update"
          KeySchema:
            - AttributeName: "driverIdKey"
              KeyType: "HASH"
            - AttributeName: "stateDate"
              KeyType: "RANGE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "bookingLocation"
              - "targetLocation"
              - "state"

Outputs:
  FrabRevalidaApi:
    Description: "API Gateway endpoint URL for prod stage for Frab Revalida API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  # FrabApiKey:
  #   Description: "API Key ID for sending requests"
  #   Value: !Ref FrabApiKey
  